### ISSUE TITLE
Example view form using the gem

### ISSUE THREAD

**Issue by ethicalhack3r** [siemens/cvss-suite#10]
It would be useful to have an example Rails view with a form that shows the Gem being used. An example calculator for example, https://www.first.org/cvss/calculator/3.1

It would save everyone from "reinventing the wheel" when they want to use the Gem.

(P.S. Thanks for the gem! I'm going to try it out.)

**Comment by oliverhamboerger** [comment]
Hi @ethicalhack3r,
thank you for this issue. Even though I think this kind of functionality would be useful, this feature is not in scope of this gem. This gem takes a vector as input and works from there. Meaning you would only need an input field which value is sent to the backend. The example from first.org you posted is much more than this. I think it would be useful to have another gem or Node.js package which provides the functionality of generating a vector.

BR
Oliver
