### ISSUE TITLE
Support only ruby >= 2.4

### ISSUE THREAD

**Issue by fwininger** [siemens/cvss-suite#19]
**Is your feature request related to a problem? Please describe.**

Can we support only ruby >= 2.4 to use new syntax and rubocop feature ?

This request has breaking change for user that use old ruby.

**Additional context**

The EOL of ruby 2.4 is 2020-03-31 and ruby 2.3 is 2019-03-31

https://www.ruby-lang.org/en/downloads/branches/

**Comment by oliverhamboerger** [comment]
I think we can drop 2.3 as of today. Let’s keep 2.4 a little while longer.
