### ISSUE TITLE
Allow parentheses in CVSS v2 vector

### ISSUE THREAD

**Issue by dfritsch86** [siemens/cvss-suite#25]
Currently, it is not possible to create a CVSSv2 from a string that contains parentheses, even though it is a valid notation of v2 vectors. 

E.g.
`CvssSuite.new('(AV:N/AC:L/Au:N/C:N/I:N/A:P/E:U/RL:OF/RC:C)') `throws an error, while
`CvssSuite.new('AV:N/AC:L/Au:N/C:N/I:N/A:P/E:U/RL:OF/RC:C')` does not.

Would it be possible to add this feature to the best CVSS gem available?

**Comment by oliverhamboerger** [comment]
Sure, I will integrate this feature into the next release.
