### ISSUE TITLE
Fixnum is deprecated warning

### ISSUE THREAD

**Issue by noraj** [siemens/cvss-suite#4]
### Subject of the issue

```ruby
irb(main):002:0> require 'cvss_suite'
/home/noraj/.gem/ruby/2.5.0/gems/cvss-suite-1.1.1/lib/cvss_suite/helpers/extensions.rb:24: warning: constant ::Fixnum is deprecated
=> true
```

Ruby 2.4.0 introduced this change: [Unify Fixnum and Bignum into Integer](https://bugs.ruby-lang.org/issues/12005).

See here for the announcement: https://www.ruby-lang.org/en/news/2016/12/25/ruby-2-4-0-released/

Also see this article discussing the issue : https://blog.bigbinary.com/2016/11/18/ruby-2-4-unifies-fixnum-and-bignum-into-integer.html (with the link to Rails PR handling the problem).

### Your environment

* version of cvss-suite gem : 1.1.1
* version of ruby : 2.5.3p105

### Steps to reproduce

In ruby 2.4+ just require the gem.

### Expected behaviour

No warning printed.

### Actual behaviour

A warning is printed.

**Comment by oliverhamboerger** [comment]
closed with #5
